#!/bin/sh
source $XDG_CONFIG_HOME/ddm/config || echo "WARNING no config found"

echo "Svn adding..."
for item in "${SVN_AUTO_ADD[@]}"
do
	svn add "$item" 2>/dev/null
done
echo "Svn committing..."
for item in "${SVN_AUTO_COMMIT[@]}"
do
	[ -r "$item" ] && echo "$item" && to_commit+=("$item")
done

svn commit -m 'natural evolution updates' "${to_commit[@]}"
