#!/bin/bash

source `which ddm-lib`

function fail ()
{
	echo "could not submit or buffer (= queue for submission) file" >&2
	exit 2
}

[ -z "$1" ] && usage
[ -z "$2" ] && usage

kind="$1"
file="$2"

[ -e "$file" ] || usage
remote_check $kind || usage

submit || buffer || fail
